services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kolobok1*
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./quest_app
    working_dir: /rails
    volumes:
      - ./quest_app:/rails
    environment:
      DATABASE_URL: postgres://postgres:Kolobok1*@db:5432/quest_app_development
      RAILS_ENV: development
    ports:
      - "3000:3000"
    command: bash -c "bundle install && ruby bin/rails db:prepare && rm -f tmp/pids/server.pid && ruby bin/rails server -b 0.0.0.0 -p 3000"
    depends_on:
      - db

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend-quest:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  pg_data: