
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "Kolobok1*") %>


development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "quest_app_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "quest_app_test") %>


production:
  primary: &primary_production
    <<: *default
    database: quest_app_production
    username: quest_app
    password: <%= ENV["quest_app_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: quest_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: quest_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: quest_app_production_cable
    migrations_paths: db/cable_migrate
